FROM ipfs/kubo:latest

# Attempt to cleanup temporary files at startup using IPFS startup logic
COPY 001-config_efs.sh /container-init.d/001-config_efs.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
